config/routes.rb
Rails.application.routes.draw do
 root 'welcome#home'
 get 'about', to: 'welcome#about'
 resources :articles
 get 'signup', to: 'users#new'
 resources :users , except: [:new]
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 5, maximum: 400}
  # validates_presence_of :user_id
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, length: { minimum:3, maximum:30 }
  validates_presence_of :name
  validates_uniqueness_of :name, :case_sensitive => false
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: {minimum:3, maximum:20 }, uniqueness: {case_sensitive: false}
  VALID_EMAIL_REGEX= /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence:true, length: {maximum:105},  uniqueness: {case_sensitive: false},
            format: {with: VALID_EMAIL_REGEX}

  has_secure_password
  # validates_presence_of :username
  # validates_uniqueness_of :username, :case_sensitive => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def required_user
    if !logged_in?
      flash[:danger] = 'Log in to perform the action'
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
 class ArticlesController < ApplicationController

   before_action :set_article, only:[:edit,:update,:show,:destroy]
   before_action :required_user, except:[:index, :show]
   before_action :required_same_user, only:[:edit,:update,:destroy]
   def new
     @article = Article.new
   end

   def edit
   end

   def index
     @articles = Article.all
     # @articles = Article.paginate(page: params[:page])
   end

   def create
     @article = Article.new(article_params)
     @article.user = current_user
     if @article.save
       flash[:success] = "Article is created successfully"
       redirect_to article_path(@article)
     else
       render :new
     end
   end

   def update
     if @article.update(article_params)
       flash[:success] = "Article is edited successfully"
       redirect_to article_path(@article)
     else
       render :edit
     end
   end

   def show
   end

   def destroy
     @article.destroy
     flash[:danger] = "Article is deleted successfully"
     redirect_to articles_path
   end

   private

   def set_article
     @article = Article.find(params[:id])
   end

    def article_params
      params.require(:article).permit(:title, :description)
    end

    def required_same_user
      unless (current_user == @article.user) || current_user.admin?
        flash[:danger] = "Your are restricted to edit this article"
        redirect_to articles_path
      end
    end

 end

app/controllers/sessions_controller.rb
 class SessionsController < ApplicationController

   def new

   end

   def create
     user = User.find_by(email: params[:session][:email].downcase)
     if (user && user.authenticate(params[:session][:password]))
       session[:user_id] = user.id
       flash[:success] = "Logged in successfully"
       redirect_to user_path(user)
     else
       flash.now[:danger] = "Invalid credentials"
       render 'new'
     end

   end

   def destroy
     session[:user_id] = nil
     flash[:success] = "Logged out successfully"
     redirect_to root_path
   end

 end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only:[:show, :edit, :update, :destroy]
  before_action :required_same_user, only:[:edit, :update]
  before_action :required_admin, only:[:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Hi #{@user.username}, Welcome to Article blog"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def index
    @users = User.all
  end

  def destroy
    @user.destroy
    flash[:danger] = "User and their articles are deleted successfully"
    redirect_to users_path
  end

  def show
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Account updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end


  private

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def required_same_user
      unless logged_in? and current_user == @user || current_user.admin?
        flash[:danger] = "You can edit only your account once you logged in"
        redirect_to articles_path
      end
    end

    def required_admin
      if logged_in? and !current_user.admin?
        flash[:danger] = "Only admin can perform the action"
        redirect_to articles_path
      end
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

 def home
   redirect_to articles_path if logged_in?
 end

 def about

 end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravator_for(user, options = {size: 80})
    gravator_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravator_url = "https://secure.gravatar.com/avatar/#{gravator_id}?s=#{size}"
    image_tag(gravator_url ,alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>
              Last modified: <b><%= time_ago_in_words(article.updated_at) %> ago </b> |
              By: <b><%= article.user.username if article.user%> </b>
            </small>
          </div>
        </div>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit the article", edit_article_path(article),class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete the article", article_path(article), method: :delete,
                                              data: {confirm: "Are you sure"},
                                              class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors',obj: @article %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |a| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= a.label :title %>
      </div>
      <div class="col-sm-8">
        <%= a.text_field :title, class: "form-control", placeholder: "Enter title", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= a.label :description %>
      </div>
      <div class="col-sm-8">
        <%= a.text_area :description, rows:10 , class: "form-control", placeholder: "Enter description" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= a.submit class: "btn btn-primary btn-lg "%>
      </div>
    </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-10">
      <%= link_to 'Cancel', articles_path, class: 'btn btn-small btn-danger' %>
    </div>
  </div>

</div>

app/views/articles/edit.html.erb
<h1 align='center'> Edit the article </h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align='center'> Listing all articles </h1>
<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<h1 align='center'> Create a new article </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align='center'> Title:<%= @article.title %></h2>
<div class="block-hight">
<div class="well col-xs-8 col-xs-offset-2 block-hight">
  <h4 class='center description'><strong>Description:</strong></h4>
  <hr>
    <%= simple_format(@article.description) %>

    <div class="article-actions">
      <% if logged_in? and (current_user == @article.user || current_user.admin?) %>
        <%= link_to "Edit the article", edit_article_path(@article),class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete the article", article_path(@article), method: :delete,
                                          data: {confirm: "Are you sure"},
                                          class: "btn btn-xs btn-danger" %>
      <% end %>
      <%= link_to "View all articles", articles_path ,class: "btn btn-xs btn-success" %>
    </div>
</div>

<% if @article.user %>
<div class="listing">
  <div class="row center">
  <div class="col-md-2">
    <div class="thumbnail">
      <p class='center'> <b> Created by: </b> </p>
      <%= link_to gravator_for(@article.user), user_path(@article.user) %>
      <div class="caption">
        <%= link_to @article.user.username, user_path(@article.user) ,class:'article-title' %>
        <p> <b> <%= pluralize(@article.user.articles.count, "article") if @article.user.articles%> </b> </p>
      </div>
    </div>
  </div>
</div>
</div>
<% end %>


</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="https://www.udemy.com"> Best cource for rails </a>
    </small>
    <nav>
      <ul>
        <li> <%= link_to 'About', about_path %> </li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name,msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class='close' data-dismiss='alert'>&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Articles Blog', root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to 'Articles', articles_path %> </li>
        <li> <%= link_to 'Users', users_path %> </li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li> <%= link_to 'New Article', new_article_path %> </li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Logout" , logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your <%= "Admin" if current_user.admin? %> profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View profile", user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in" , login_path %></li>
          <li><%= link_to "Sign up" , signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trynew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
     <%# <%= debug(params) if Rails.env.development? %> 
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class='panel-title'>
            <%= pluralize(obj.errors.count,"error") %>
            Prohibited this article from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors',obj: @user %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |a| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= a.label :username %>
      </div>
      <div class="col-sm-8">
        <%= a.text_field :username, class: "form-control", placeholder: "Enter name", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= a.label :email %>
      </div>
      <div class="col-sm-8">
        <%= a.email_field :email, class: "form-control", placeholder: "Enter email" %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= a.label :password %>
      </div>
      <div class="col-sm-8">
        <%= a.password_field :password, class: "form-control", placeholder: "Enter password" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= a.submit(@user.new_record? ?  "Sign up" : "Update account", class: "btn btn-primary btn-lg") %>
      </div>
    </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-10">
      <%= link_to 'Cancel', articles_path, class: 'btn btn-small btn-danger' %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align='center'>Edit your account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align='center'> All blog users</h1>
<% @users.each do |user| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li> <%= link_to gravator_for(user), user_path(user) %>
          <%= link_to user.username, user_path(user) ,class:'article-title col-md-offset-2' %>
        </li>
        <li class='center'><small> <b><%= pluralize(user.articles.count, "article") if user.articles%> </b> </small> </li>
        <% if logged_in? and current_user.admin? and current_user!=user %>
           <li align = 'right'>
             <%= link_to "Delete user", user_path(user), method: :delete,
                    data: {confirm: "Are you sure you want to delete the user and all their articles?"},
                    class: "btn btn-xs btn-danger" %>
           </li>
        <% end %>
      </div>
    </div>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1 align='center'> Signup for blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align='center'> Welcome <%= @user.username %> page </h1>
<div class="row">
  <div class="col-md-s center">
    <%= gravator_for @user , size: 150 %>
  </div>
</div>
<h4 align='center'> <%= @user.username %> articles </h4>
<%= render 'articles/article', obj: @user.articles %> 

app/views/welcome/about.html.erb
<h1> This is the about page </h1>
<%= link_to 'Home',root_path %>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1> Articles Blog </h1>
  <%= link_to 'Sign up now', signup_path, class: "btn btn-primary btn-lg btn-exlarge" %>
</div>